# Generated by Django 3.1.5 on 2021-03-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20210204_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'На ремонте'), ('o', 'На руках'), ('a', 'Доступна'), ('r', 'Забронирована')], default='m', help_text='Book availability', max_length=1),
        ),
    ]
